Adding introducion and applying new theme from handbook theme
PauloniaAQP/paulonia_handbook pull request #15
Opened 2022-05-09 15:37 UTC by jhuni45

2022-05-09 16:03 UTC, juanleondev requested changes

2022-05-09 16:03 UTC, juanleondev commented on paulonia/index.md
> +Hemos creado este manual, bajo los principios de la transparencia y motivación de estar transformando continuamente la forma en la dirigimos la empresa, para así mejorar nuestra capacidad de crear, e
```suggestion
Hemos creado este manual, bajo los principios de la transparencia y motivación de estar transformando continuamente la forma en la que dirigimos la empresa, para así mejorar nuestra capacidad de crear, expandirnos y brindar la mejor experiencia a nuestros clientes y compañeros de trabajo.
```

2022-05-10 01:24 UTC, ChrisChV requested changes

2022-05-10 01:24 UTC, ChrisChV commented on paulonia/lifecycle/comercial.md
> +---
@jhuni45 Aća irá la parte de comercial? Veo que se ha cambiado el título pero no veo el contenido

2022-05-11 13:19 UTC, texsmv reviewed
Revisar las preguntas y sugerencias de Chris y Juan

2022-05-26 20:45 UTC, juanleondev approved these changes

2022-05-27 22:30 UTC, texsmv approved these changes

2022-05-30 18:29 UTC, jhuni45 commented on paulonia/lifecycle/comercial.md
> +---
@ChrisChV Si, por favor crea un task para que se haga al menos este proceso inicial

2022-05-30 20:17 UTC, ChrisChV approved these changes

2022-05-30 20:18 UTC, merged