Adding introduction for processes section
PauloniaAQP/paulonia_handbook pull request #17
Opened 2022-05-30 20:54 UTC by jhuni45

2022-05-31 20:49 UTC, texsmv approved these changes

2022-06-02 14:14 UTC, juanleondev requested changes

2022-06-02 14:14 UTC, juanleondev commented on paulonia/processes/index.md
> +A veces, los procesos descritos en este manual, puede no coincidir con la forma en la que se maneja Paulonia en la actualidad, pero estamos seguros que cuando aparezcan nuevos problemas, Paulonia se
Creo que no debemos poner esto, es como quitarle validez al handbook. Lo que podriamos poner es que constantemente estamos mejorando los procesos y actualizando esta sección.

2022-06-03 13:27 UTC, jhuni45 commented on paulonia/processes/index.md
> +A veces, los procesos descritos en este manual, puede no coincidir con la forma en la que se maneja Paulonia en la actualidad, pero estamos seguros que cuando aparezcan nuevos problemas, Paulonia se
@juanleondev  Creo que a las finales es lo mismo. Y si puse eso es porque van a haber cosas que no van a coincidir en nada. Por ejemplo en el proceso de reclutamiento, ya tenemos un proceso definido, pero ahora vamos a lanzar un proceso que no tiene nada que ver, por que no buscamos un perfil de Flutter.

2022-06-03 14:29 UTC, texsmv commented on paulonia/processes/index.md
> +A veces, los procesos descritos en este manual, puede no coincidir con la forma en la que se maneja Paulonia en la actualidad, pero estamos seguros que cuando aparezcan nuevos problemas, Paulonia se
@jhuni45 entiendo más o menos a lo que te refieres, tal vez podríamos cambiar la forma de escribirlo. Tipo: 'En Paulonia estamos mejorando constantemente, esto significa que nuestros procesos se van actualizando. Este handbook se actualizará constantemente. Si tienes alguna duda sobre algún proceso, no dudes en contactarnos.' Para que no suene como que se le quita validez.

2022-06-03 15:01 UTC, ChrisChV commented on paulonia/processes/index.md
> +A veces, los procesos descritos en este manual, puede no coincidir con la forma en la que se maneja Paulonia en la actualidad, pero estamos seguros que cuando aparezcan nuevos problemas, Paulonia se
Concuerdo :arrow_double_up:

2022-06-07 14:21 UTC, ChrisChV approved these changes

2022-06-14 14:59 UTC, ChrisChV commented
@juanleondev Pequeño recordatorio de que falta una segunda revisión aquí

2022-06-20 15:11 UTC, ChrisChV commented
@juanleondev Pequeño recordatorio de que falta una segunda revisión aquí

2022-06-22 11:44 UTC, juanleondev approved these changes

2022-06-22 15:07 UTC, merged