added initial section of comercial area
PauloniaAQP/paulonia_handbook pull request #2
Opened 2022-01-14 13:57 UTC by juanjoseleca

2022-01-17 16:43 UTC, ChrisChV requested changes
@juanjoseleca Suggestion of some changes

2022-01-17 16:43 UTC, ChrisChV commented on commercial/index.md
> +﻿# Área Comercial
Here the title goes in the parámeters:
```suggestion
---
title: Área comercial
lead: true
---
```

2022-01-17 16:43 UTC, ChrisChV commented on commercial/index.md
> +- **Asistente de prospección**
In this list, I suggest putting the content next to the title: Ex 

```
**Gerente de ventas:** Es el encargado de dirigir la estrategia para la obtención de nuevos clientes, y verificar el proceso de venta.
```

2022-01-17 16:43 UTC, ChrisChV commented on commercial/index.md
> +- **Google Forms**
The same of above

2022-01-17 21:02 UTC, jhuni45 requested changes
I think, this section could improve on all descriptions, and I dont know if its necessary put specific tools like "Gmail", maybe we can put "Email"

2022-01-17 21:02 UTC, jhuni45 commented on commercial/index.md
> +Se debe prestar atención a dichos canales para mantener un flujo constante de prospectos. Luego de tener algun interesado en los servicios de Paulonia, se procede a agendar una reunión para la revisi
To correct: algún

2022-01-20 23:46 UTC, texsmv commented on commercial/index.md
> +- **Gmail**
Esta me parece una herramienta muy genérica, incluso se podría usar alternativas que son mejores.

2022-01-20 23:55 UTC, texsmv approved these changes
Creo que está bien como primera versión, pero creo que faltan cosas que agregar. A mi parecer el área comercial debería tener más funciones  (ejemplo: buscar nuevas estrategias para obtener clientes, investigar el mercado ... ) y una mejor descripción de las cualidades para algunos puestos (cosas coma comunicación, persuasión ...).

2022-02-05 02:59 UTC, ChrisChV approved these changes

2022-02-05 03:01 UTC, ChrisChV commented
@jhuni45 @texsmv A criterio de @juanleondev se va a publicar esta primera versión del documento, sus sugerencias de mejora quedarán registradas para una siguiente tarea de seguimiento: https://paulonia.atlassian.net/browse/TOMENTOSA-1508

2022-02-05 03:03 UTC, merged