Cambios generales en todo el área de Paulonia Studios
PauloniaAQP/paulonia_handbook pull request #21
Opened 2022-06-10 21:42 UTC by gabyrojascas

2022-06-13 22:51 UTC, jhuni45 requested changes

2022-06-13 22:51 UTC, jhuni45 commented on studios/roles.md
> +Es un miembro del equipo que tenga asignada una tarea relacionada al diseño de experiencia (UX) de producto. Este rol también puede ser tomado por el Team lead, Project lead o Product designer. Tiene
```suggestion
Es un miembro del equipo que tenga asignada una tarea relacionada al diseño de experiencia (UX) de producto. Este rol también puede ser tomado por el Team Lead, Project Lead o Product Designer. Tiene las siguientes responsabilidades:
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/roles.md
> +- El diseñador UX tiene la obligación de cumplir sus tareas asignadas de la mejor forma posible, cumpliendo con lo descrito en cada tarea.
```suggestion
- Tiene la obligación de cumplir sus tareas asignadas de la mejor forma posible, cumpliendo con lo descrito en cada tarea.
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/roles.md
> +- Tener conocimiento y habilidades en las tecnologías y metodologías que demande el proyecto.
```suggestion
- Tener conocimiento y habilidades en las tecnologías y metodologías que demande su rol.
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/roles.md
> +- El diseñador UI se compromete a cumplir con todas sus tareas asignadas antes del fin del sprint para evitarcualquier tipo de retrasos. Si a mitad del sprint se da cuenta de que no va a poder termin
```suggestion
- Cumplir con todas sus tareas asignadas antes del fin del Sprint para evitar cualquier tipo de retraso. Si a mitad del Sprint se da cuenta de que no va a poder terminar alguna tarea, debe comunicarlo inmediatamente al Project Lead o al Reviewer de la tarea.
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/roles.md
> +La persona elejida tiene que tener las siguientes características:
```suggestion
La persona elegida tiene que tener las siguientes características:
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/roles.md
> +Es cualquier miembro del equipo que tenga que revisar una tarea. Este rol también puede ser tomado por el Team lead y el Project lead. Tiene las siguientes responsabilidades:
```suggestion
Es cualquier miembro del equipo que tenga que revisar una tarea. Este rol también puede ser tomado por el Team Lead y el Project Lead. Tiene las siguientes responsabilidades:
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/roles.md
> +- No comprometerse a realizar tareas con un Score mayor a 13.
Ya no estamos aplicando esta metodologa. Borrar

2022-06-13 22:51 UTC, jhuni45 commented on studios/documentos_oficiales.md
> +Existe documentación oficial y stándar, para algunas de las etapas de diseño. Los inputs o los outputs que requieran algún documento tienen que ser bajo los enlazados aquí.
Cambiar "y estándar" por "documentación oficial base". La segunda parte no tiene sentido. Revisar

2022-06-13 22:51 UTC, jhuni45 commented on studios/documentos_oficiales.md
> +El briefing inicial tiene como propósito conocer de cerca y formalmente la idea inicial  del cliente, en este **[Briefing](https://form.jotform.com/221434741955660)** plasmamos preguntas generales pa
```suggestion
El Briefing inicial tiene como propósito conocer de cerca y formalmente la idea inicial del cliente, en este **[Briefing](https://form.jotform.com/221434741955660)** plasmamos preguntas generales para conocer lo que necesita el cliente.
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/documentos_oficiales.md
> +Documentos y necesarios para una prueba moderada.
Completar, que no tiene sentido

2022-06-13 22:51 UTC, jhuni45 commented on studios/documentos_oficiales.md
> +Este **[documento](https://drive.google.com/file/d/1NzKaZVt709fjiVfGtCQhIB3I850sKDHJ/view?usp=sharing)**  es la primera versión de nuestro documento general de testing, reprensenta el esqueleto  para
```suggestion
Este **[documento](https://drive.google.com/file/d/1NzKaZVt709fjiVfGtCQhIB3I850sKDHJ/view?usp=sharing)**  es la primera versión de nuestro documento general de testing, reprensenta el esqueleto para que una vez dadas las sesiones de prueba, el docuemnto esté listo para ser rellenado con los hallazgos de cada participante.
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/documentos_oficiales.md
> +Basado en el documento de *pre testing*, una vez finalizado las sesiones de prueba con los usuarios, procedemos a generar el reporte final de usabilidad este reporte debe regirse al siguiente **[docu
```suggestion
Basado en el documento de *pre testing*, una vez finalizado las sesiones de prueba con los usuarios, procedemos a generar el reporte final de usabilidad. Este reporte debe regirse al siguiente **[documento](https://drive.google.com/file/d/1IhlEkGdBMh-aUFWmK2z6_oBDRy5LlCXa/view?usp=sharing)** y debe ser el entregable final de esta etapa.
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/processdesign/benchmark.md
> +  - Identificar el valor agregado y la industria a la que pertenece nuestro producto.
Esto no es un output inicial creo. O debe tener una mejor explicacion

2022-06-13 22:51 UTC, jhuni45 commented on studios/processdesign/benchmark.md
> +  - Documentar y categorizar el benchmarking plasmado en el entorno de trabajo bajo el estándar vigente.
```suggestion
  - Documentación y categorización el benchmarking plasmado en el entorno de trabajo bajo el estándar vigente.
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/processdesign/media_fidelidad.md
> +  - Formulario **[Briefing](https://form.jotform.com/221434741955660)** enviado por el cliente
Ya se pidio, y creo que aqui ya no es necesario. Borrar

2022-06-13 22:51 UTC, jhuni45 commented on studios/processdesign/benchmark.md
> +  - Entorno de trabajo configurado
Esto ya no se debe pedir

2022-06-13 22:51 UTC, jhuni45 commented on studios/processdesign/media_fidelidad.md
> +  - Entorno de trabajo configurado
Ya no es necesario

2022-06-13 22:51 UTC, jhuni45 commented on studios/processdesign/alta_fidelidad.md
> +  - Formulario **[Briefing](https://form.jotform.com/221434741955660)** enviado por el cliente
no lo veo necesario

2022-06-13 22:51 UTC, jhuni45 commented on studios/processdesign/alta_fidelidad.md
> +  - Entorno de trabajo configurado
no es necesario

2022-06-13 22:51 UTC, jhuni45 commented on studios/processdesign/testing.md
> +  - Expocisión al cliente
```suggestion
  - Exposisción al cliente
```

2022-06-13 22:51 UTC, jhuni45 commented on studios/processdesign/testing.md
> +Finalmente se genera un reporte con todas las observaciones y conclusiones de las pruebas, a partir de aquí se toman decisiones juntamente con el cliente que pueden implicar cambios en diseño, enfoqu
```suggestion
Finalmente se genera un reporte con todas las observaciones y conclusiones de las pruebas, a partir de aquí se toman decisiones juntamente con el cliente que pueden implicar cambios en diseño, enfoque, negocio, etc.
```

2022-06-14 14:08 UTC, juanleondev commented on studios/processdesign/testing.md
> +  - Expocisión al cliente
Aqui es exposición jeje

2022-06-14 14:12 UTC, juanleondev requested changes
En general lo veo bien, solo habria que resaltar con cursiva las palabras en ingles, u optar por tener todo en español (aunque para algunos terminos lo mas entendible es mantenerlo en ingles)

2022-06-14 14:57 UTC, ChrisChV requested changes
@gabyrojascas Buen trabajo, lo veo bien, sólo algunos pequeños fixes de mi parte sobre algunas líneas comentadas de `quotes` que he visto en varios documentos. Si no se va a usar es mejor borrarlas que dajarlas comentadas

2022-06-14 14:57 UTC, ChrisChV commented on studios/documentos_oficiales.md
> +    #author: Jef Raskin
Si no se va a usar sería mejor eliminarlo

2022-06-14 14:57 UTC, ChrisChV commented on studios/processdesign/alta_fidelidad.md
> +    #authorPosition: about Human Computer Interfaces
Si no se va a usar mejor borrarlo

2022-06-21 22:28 UTC, juanleondev requested changes

2022-06-24 14:53 UTC, ChrisChV approved these changes

2022-06-24 15:16 UTC, texsmv commented on studios/processdesign/alta_fidelidad.md
> +  - Documento de requerimientos
Una duda, el documento de requerimientos tiene algun formato especifico?

2022-06-24 15:16 UTC, texsmv approved these changes
LGTM

2022-06-30 01:51 UTC, jhuni45 approved these changes

2022-07-07 19:09 UTC, jhuni45 commented on studios/processdesign/alta_fidelidad.md
> +  - Documento de requerimientos
@texsmv No, no hay un formato en especifico, de esto creo que se debe encargar comercial.

2022-07-12 21:04 UTC, gabyrojascas commented
@ChrisChV ya se hizo los pequeños cambios

2022-07-14 14:55 UTC, merged