[TOMENTOSA-2126] Introduction to security
PauloniaAQP/paulonia_handbook pull request #22
Opened 2022-06-20 15:29 UTC by ChrisChV

2022-06-20 17:20 UTC, jhuni45 requested changes

2022-06-20 17:20 UTC, jhuni45 commented on paulonia/security/security.md
> +- Contienen información financiera o situacional de Paulonia.
```suggestion
- Contiene información financiera o situacional de Paulonia.
```

2022-06-20 17:20 UTC, jhuni45 commented on paulonia/security/security.md
> +- Contienen información financiera o situacional de Paulonia.
@ChrisChV por "situacional" imagino que te refieres al estado actual de la empresa no ? Podriamos buscar otro término

2022-06-20 17:20 UTC, jhuni45 commented on paulonia/security/security.md
> +Si eres desarrollador y eres activo en Github, es necesario que configures llaves de acceso a Github. Ya que al activar el 2FA, ahora es necesario hacer todas las operaciones mediante SSH. Para confi
@ChrisChV Para toda esta sección creo que debemos poner un titulo, para que sea mas facil linkear o encontrar

2022-06-20 17:20 UTC, jhuni45 commented on paulonia/security/security.md
> +Lo primero que siempre tenemos que tener segura es nuestra herramienta principal: nuestra laptop o computadora con la cual trabajamos. Es el punto de entrada a mucha información: cuentas, documentos,
```suggestion
Lo primero que siempre tenemos que tener seguro, es nuestra herramienta principal: nuestra laptop o computadora con la cual trabajamos. Es el punto de entrada a mucha información: cuentas, documentos, códigos, etc. Por esta razón debemos de tener en cuenta los siguientes puntos:
```

2022-06-20 17:20 UTC, jhuni45 commented on paulonia/security/security.md
> +- En caso de robo, avisar a tu team lead para hacer una rotación de las credenciales que se te proporcionaron y se usaron en la computadora. Además, desde otro dispositvo deberás cerrar sesión en tod
```suggestion
- En caso de robo o pérdida, avisar a tu team lead para hacer una rotación de las credenciales que se te proporcionaron y se usaron en la computadora. Además, desde otro dispositvo deberás cerrar sesión en todas las cuentas que usabas en tu computadora.
```

2022-06-20 17:20 UTC, jhuni45 commented on paulonia/security/security.md
> +- En caso de robo, avisar a tu team lead para hacer una rotación de las credenciales que se te proporcionaron y se usaron en el celular. Además, desde otro dispositivo deberás cerrar sesión en todas
```suggestion
- En caso de robo o pérdida, avisar a tu team lead para hacer una rotación de las credenciales que se te proporcionaron y se usaron en el celular. Además, desde otro dispositivo deberás cerrar sesión en todas las cuentas que usabas en tu celular
```

2022-06-21 22:36 UTC, juanleondev requested changes

2022-06-21 22:36 UTC, juanleondev commented on paulonia/security/security.md
> +Dependiendo del área de Paulonia en que trabaje, se van a usar diferentes cuentas. Dependiendo de su importancia, cada team lead se va a encargar de dar los lineamientos adecuados. Pero hay cuentas q
```suggestion
Dependiendo del área de Paulonia en que trabaje, se van a usar diferentes cuentas. Según el nivel de importancia, cada team lead se va a encargar de dar los lineamientos adecuados. Pero hay cuentas que todos dentro de Paulonia usamos: Correo de Google, Slack, Github. Una cuenta es considerada crítica si cumple con alguno de los siguientes puntos:
```

2022-06-22 11:27 UTC, juanleondev approved these changes

2022-06-24 14:43 UTC, texsmv approved these changes

2022-06-24 15:02 UTC, ChrisChV commented on paulonia/security/security.md
> +Si eres desarrollador y eres activo en Github, es necesario que configures llaves de acceso a Github. Ya que al activar el 2FA, ahora es necesario hacer todas las operaciones mediante SSH. Para confi
@jhuni45  Pero si tiene título :thinking:

2022-06-24 15:03 UTC, ChrisChV commented on paulonia/security/security.md
> +Si eres desarrollador y eres activo en Github, es necesario que configures llaves de acceso a Github. Ya que al activar el 2FA, ahora es necesario hacer todas las operaciones mediante SSH. Para confi
@jhuni45 pero sí tiene título :thinking: O a qué parte te refieres?

2022-06-24 15:10 UTC, ChrisChV commented
@jhuni45 esta listo para otro review

2022-06-27 22:21 UTC, jhuni45 approved these changes

2022-06-27 22:21 UTC, jhuni45 commented
@ChrisChV approved

2022-06-29 13:01 UTC, merged