Financial document created
PauloniaAQP/paulonia_handbook pull request #24
Opened 2022-10-06 22:08 UTC by ChrisChV

2022-10-07 14:18 UTC, texsmv approved these changes

2022-10-17 15:51 UTC, jhuni45 requested changes

2022-10-17 15:51 UTC, jhuni45 commented on paulonia/processes/financial.md
> +
```suggestion
Estas tareas se realizan en el momento en que ocurre un hecho: hay un ingreso, egreso, nueva factura, etc. No toman mucho tiempo si se realizan en el momento. 

```

2022-10-17 15:51 UTC, jhuni45 commented on paulonia/processes/financial.md
> +2. Dar una revisión rápida de los reportes; que las horas coincidan con lo calculado en el excel.
Indicar qe Excel es ?

2022-10-17 15:51 UTC, jhuni45 commented on paulonia/processes/financial.md
> +4. Recursos humanos se encarga de los trabajadores en planilla. Recursos humanos nos envía la boleta de pago de cada trabajador en planilla.
```suggestion
4. El área de Recursos Humanos se encarga de los trabajadores en planilla. Dicha área nos envía la boleta de pago de cada trabajador en planilla.
```

2022-10-17 15:51 UTC, jhuni45 commented on paulonia/processes/financial.md
> +Antes de enviar los documentos a la contadora es necesario verificar y cerrar el historial del mes que ha pasado. Además se tiene que crear la carpeta para el siguiente mes.
```suggestion
Antes de enviar los documentos a contaduría es necesario verificar y cerrar el historial del mes que ha pasado. Además se tiene que crear la carpeta para el siguiente mes.
```

2022-10-17 15:51 UTC, jhuni45 commented on paulonia/processes/financial.md
> +5. Buscar las constancias de pago o facturas de cada transacción y agregar el link en el campo *documento*
```suggestion
5. Buscar las constancias de pago o facturas de cada transacción y agregar el enlace en el campo *documento*
```

2022-10-17 15:51 UTC, jhuni45 commented on paulonia/processes/financial.md
> +8. Enviar por correo el comprimido a la contadora.
```suggestion
8. Enviar por correo el comprimido a contaduría.
```

2022-10-17 15:52 UTC, jhuni45 commented
@ChrisChV revisión lista, al pendiente de los cambios

2022-10-28 12:52 UTC, ChrisChV commented
@jhuni45 Gracias por el feedback. Está lista para una segunda revisión.

@juanleondev No olvide su revisión aquí

2022-11-14 13:41 UTC, ChrisChV commented
@juanleondev don't forget this review

2022-12-14 00:46 UTC, ChrisChV commented
The PR has more than a month, deploying by acceptance of the majority

2022-12-14 00:46 UTC, merged