Initial version maintenance process
PauloniaAQP/paulonia_handbook pull request #3
Opened 2022-02-11 15:03 UTC by jhuni45

Some fields are still missing, this is an initial version (not stable)

2022-02-11 15:18 UTC, jhuni45 commented
### Guys, if you have some questions that need to be mentioned, please leave it here or by slack

2022-02-16 11:54 UTC, juanleondev requested changes

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/frequestions.md
> +Se refiere a toda petición de ca    mbio, modificación, actualización, resolución de errores, que velen por el bienestar de un sistema, asegurando su completo funcionamiento y usabilidad del mismo.
No se si es mi navegador pero  cambio aparece como "cam       bio"

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/frequestions.md
> +Se refiere a toda petición de ca    mbio, modificación, actualización, resolución de errores, que velen por el bienestar de un sistema, asegurando su completo funcionamiento y usabilidad del mismo.
Eliminar "del mismo" ya que es redudante.

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/frequestions.md
> +Sin embargo, si se realiza una solicitud de mantenimiento en las fechas finales de un mes y se espera que se resuelvan ese mismo mes, existe un algo riesgo de no ser analizado ni atendido.
cambiar **algo** por **alto**. Y en la ultima parte pondria, existe un alto riesgo de no ser atendido en el plazo solicitado.

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/frequestions.md
> +Cada mes durante la vigencia del contrato de mantenimiento, el personal de Paulonia le destinará cierto monto de horas para atender las solicitudes de mantenimiento aprobadas.
aqui cambiar *le destinará* por *destinará*

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/frequestions.md
> +> Paulonia le destina 20 horas en todo el mes de Enero para resolver sus solicitudes de mantenimiento. Se tienen 3 solicitudes cuyas horas estimadas de resolución son:
Aqui igual el **le destina** por **destina**

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/frequestions.md
> +Estas solicitudes pasan a ser aprobadas y resueltas (ya no se analizan, a no ser que haya surtido algún cambio) al siguiente mes.
**surtido**  por **surgido**

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/frequestions.md
> +#### ¿Cómo se analiza las solicitudes perfectivas?
No me queda claro el concepto de solicitudes perfectivas, se podria añadir una pregunta explicando o cambiando el termino.

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/maintenance.md
> +La fase de mantenimiento compete netamente al proceso de cambiar, modificar o actualizar un proyecto, bajo el principio de siempre atender la necesidad de los usuarios o conservar la estabilidad del
Aqui siento que el termino  **compete**  no encaja bien, se podria cambiar por **comprende**, tambien el **netamente** por **únicamente**.

Abajo cambiar el **haya sido desplegado por Paulonia o no** por **haya sido hecho por Paulonia o no**, para no repetir el mismo termino.

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/maintenance.md
> +    + Si se llegara a exceder el límite de esta [BOLSA](../frequestions/#%C2%BFqu%C3%A9-es-una-bolsa) , esto se verá reflejado en su factura de cada mes. *¡Tenga cuidado!*
Aqui tal ves indicar que el tiene el control sobre le limite maximo de horas facturadas (El equipo de desarrollo o diseño imagino debe alertar cuando se vaya a sobrepasar el maximo de horas). Para que el cliente no tenga el temor de que se exceda en la bolsa y se le cobre un monto superior al que tiene asignado por mes

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/frequestions.md
> +#### ¿Cómo se analiza las solicitudes perfectivas?
Creo que esto se menciona en otra seccion, en ese caso no hay problema

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/maintenance.md
> +Recuerde que existen varias áreas en Paulonia, y un evento a atender puede demandar la atención de una o todas ellas, y esto determinará que se extienda o contraiga el tiempo de entrega. Así mismo, r
En **una o todas ellas** no se si refiere a evento o a otra cosa, hay que especificar si no se ha mencionado antes.

2022-02-16 11:54 UTC, juanleondev commented on paulonia/lifecycle/maintenance.md
> ++ Si los cambios demandaran la generación de una nueva versión y APK, las horas gastadas para generar su Release también se factura.
cambiaria la segunda parte por **las horas destinadas a ello también se facturarán**

2022-02-16 14:00 UTC, texsmv commented on paulonia/lifecycle/frequestions.md
> +Se refiere a toda petición de ca    mbio, modificación, actualización, resolución de errores, que velen por el bienestar de un sistema, asegurando su completo funcionamiento y usabilidad del mismo.
Igual a mi.

2022-02-16 14:02 UTC, texsmv commented on paulonia/lifecycle/frequestions.md
> +#### ¿Qué es una solicitud de mantenimiento?
Maybe, seria bueno resaltar cuando es que el proceso de mantenimiento empieza.

2022-02-16 14:09 UTC, texsmv commented on paulonia/lifecycle/maintenance.md
> +| **Perfectivo**<br />(Prioritario)   | Si desea mejorar su aplicación añadiendo nuevas funcionalidades o modificando las ya existentes, que recae en un alto grado de alteración del código fuente.*Te
No estoy seguro de esto de agregar nuevas funcionalidades, eso es parte del proceso de mantenimiento? No podria pasar que un cliente crea que su app sigue desarrollandose?

2022-02-16 14:10 UTC, texsmv requested changes
Porfa responder a mis dudas, para aprobarlo.

2022-02-17 01:53 UTC, ChrisChV requested changes

2022-02-17 01:53 UTC, ChrisChV commented on paulonia/lifecycle/frequestions.md
> +## 1. Conceptos generales
He visto que este es el único header que tiene número, creo que se debería borrar o agregar número a los otros headers

2022-02-17 01:53 UTC, ChrisChV commented on paulonia/lifecycle/maintenance.md
> +| **Perfectivo**<br />(Prioritario)   | Si desea mejorar su aplicación añadiendo nuevas funcionalidades o modificando las ya existentes, que recae en un alto grado de alteración del código fuente.*Te
Acá creo que habría que poner que es recomendable que este tipo de eventos sean mejor hacerse en una nueva versión ya que puede que consuma todas sus horas de la bosa; pero tampoco cerrarse a recibirlos, porque sí hay cositas pequeñas (ejemplo agregar un campo más y así) que no demoran tanto y pueden entrar sin problemas en la bolsa. Igual también depende del análisis

2022-02-17 01:53 UTC, ChrisChV commented on paulonia/lifecycle/maintenance.md
> +2. **Basado en pruebas o réplicas**: El revisor necesita iniciar con pequeñas pruebas o réplicas que pudo causar el evento, para determinar el costo de tiempo.
Creo que acá también hay que poner la opinión del cliente, ya que en algun momento el cliente pueda querer priorizar algunos más que otros

2022-02-17 01:53 UTC, ChrisChV commented on paulonia/lifecycle/maintenance.md
> ++ Si los cambios demandaran la actualización en tiendas, se coordinará con el área de Administración de tiendas para la actualización de contenido multimedia de cada tienda. Así mismo este proceso se
```suggestion
+ Si los cambios demandan la actualización en tiendas, se coordinará con el área de Administración de tiendas para la actualización de contenido multimedia de cada tienda. Así mismo este proceso se hará bajo los acuerdos especificados en [TODO]
```

2022-02-18 13:02 UTC, jhuni45 commented on paulonia/lifecycle/frequestions.md
> +Se refiere a toda petición de ca    mbio, modificación, actualización, resolución de errores, que velen por el bienestar de un sistema, asegurando su completo funcionamiento y usabilidad del mismo.
done

2022-02-18 13:04 UTC, jhuni45 commented on paulonia/lifecycle/frequestions.md
> +Sin embargo, si se realiza una solicitud de mantenimiento en las fechas finales de un mes y se espera que se resuelvan ese mismo mes, existe un algo riesgo de no ser analizado ni atendido.
@juanleondev  Pero el cliente no pide ningun plazo, solo lo reporta, no? o a que te refiere con el plazo solicitado?

2022-02-18 13:19 UTC, jhuni45 commented on paulonia/lifecycle/maintenance.md
> +    + Si se llegara a exceder el límite de esta [BOLSA](../frequestions/#%C2%BFqu%C3%A9-es-una-bolsa) , esto se verá reflejado en su factura de cada mes. *¡Tenga cuidado!*
@juanleondev Como el cliente tiene el control sobre el límite de horas?

2022-02-18 13:21 UTC, jhuni45 commented on paulonia/lifecycle/maintenance.md
> +Recuerde que existen varias áreas en Paulonia, y un evento a atender puede demandar la atención de una o todas ellas, y esto determinará que se extienda o contraiga el tiempo de entrega. Así mismo, r
@juanleondev no entendí el comentario

2022-02-18 13:24 UTC, jhuni45 commented on paulonia/lifecycle/maintenance.md
> +| **Perfectivo**<br />(Prioritario)   | Si desea mejorar su aplicación añadiendo nuevas funcionalidades o modificando las ya existentes, que recae en un alto grado de alteración del código fuente.*Te
Claro @texsmv y @ChrisChV esto se resuelve en la sección de preguntas frecuentes, voy a linkearlo a ese documento para "forzarlo" a reconsiderar un evento de nueva funcionalidad

2022-02-18 13:25 UTC, jhuni45 commented on paulonia/lifecycle/frequestions.md
> +## 1. Conceptos generales
@ChrisChV si amego no lo cambie porque me dio pereza cambiar los links, en esta versión los cambio

2022-02-18 13:34 UTC, juanleondev commented on paulonia/lifecycle/frequestions.md
> +Sin embargo, si se realiza una solicitud de mantenimiento en las fechas finales de un mes y se espera que se resuelvan ese mismo mes, existe un algo riesgo de no ser analizado ni atendido.
@jhuni45 Arriba pusiste "y se espera que se resuelva ese mismo mes" ahi se esta definiendo una plazo, y al final añadi lo del plazo solicitado para hacer que el cliente no crea que su solicitud no sera atendida nunca.

2022-02-18 13:35 UTC, juanleondev commented on paulonia/lifecycle/maintenance.md
> +    + Si se llegara a exceder el límite de esta [BOLSA](../frequestions/#%C2%BFqu%C3%A9-es-una-bolsa) , esto se verá reflejado en su factura de cada mes. *¡Tenga cuidado!*
@jhuni45 Similar a BizzyChain, el cliente define una bolsa de horas. No se puede exceder ese limite porque el cliente no puede pagar mas de ese monto por mes.

2022-02-18 13:38 UTC, juanleondev commented on paulonia/lifecycle/maintenance.md
> +Recuerde que existen varias áreas en Paulonia, y un evento a atender puede demandar la atención de una o todas ellas, y esto determinará que se extienda o contraiga el tiempo de entrega. Así mismo, r
Lo volví a leer y haces referencia a las areas de paulonia. Esta bien, my bad.

2022-02-26 17:33 UTC, ChrisChV approved these changes

2022-02-26 17:38 UTC, ChrisChV commented
I updated the backend maintenance document and I updated the TODOs with the respective task

2022-03-05 00:40 UTC, juanleondev approved these changes

2022-03-05 02:35 UTC, merged