This is an initial version of vacation process
PauloniaAQP/paulonia_handbook pull request #4
Opened 2022-03-08 21:12 UTC by jhuni45

2022-03-09 02:06 UTC, ChrisChV requested changes
@jhuni45 Dejé algunos comentarios y faltaría solucionar los conflictos con tu anterior PR

2022-03-09 02:06 UTC, ChrisChV commented on paulonia/processes/vacation.md
> +1. Verifica en el [Calendario Paulonia](https://github.com/PauloniaAQP/paulonia_handbook/blob/main/contribute/example.md) que alguien más no haya reservado tus días de descanso
@jhuni45 Acá creo que falta cambiar el link de `Calendario Paulonia`

2022-03-09 02:06 UTC, ChrisChV commented on paulonia/processes/vacation.md
> +    +
@jhuni45 Creo que hay que colocar a la gente a ponga el estado `De vacaciones` en slack,  y abajo que lo quite o que auncie su regreso

2022-03-09 02:06 UTC, ChrisChV commented on paulonia/processes/vacation.md
> +TODO
@jhuni45 Supongo que acá se refiere a cualquier tipo de vacaciones que sean menor a 1 semana o mayor a 3 o que salgan del tiempo necesario para pedir las vacaciones?

2022-03-09 02:13 UTC, ChrisChV commented on paulonia/processes/vacation.md
> +    +
También el avisar unos días antes de irse, porque ocurre que alguién planea vacaciones 4 semanas antes y la gente se olvida. Tal vez una semana antes de irse volver a recordar o en un sprint review o restrospective volver a recordarles que se va

2022-03-15 22:23 UTC, jhuni45 commented on paulonia/areas/personal.md
> +---
@ChrisChV tiene que ser otra tarea porque debemos definir primero los puestos corporativos

2022-03-15 22:24 UTC, jhuni45 commented on paulonia/processes/vacation.md
> +4. [Salida e ingreso](#salida-e-ingreso)
Sip sorry no lo actualice

2022-03-15 22:25 UTC, jhuni45 commented on paulonia/processes/vacation.md
> +    + Estos 15 días pueden ser tomados en cualquier periodo semanal a lo largo del siguiente año
claro, por eso quiero definir los puestos corporativos

2022-03-15 22:27 UTC, jhuni45 commented on paulonia/processes/vacation.md
> +    +
va

2022-03-15 22:28 UTC, jhuni45 commented on paulonia/processes/vacation.md
> +TODO
esto tenemos que definir por eso lo deje vacio

2022-03-19 00:17 UTC, texsmv commented on paulonia/lifecycle/introduction.md
> +Creo que sería bueno poder explicar aqui el ciclo de vida cuando iniciamos un proyecto
Creo que este tipo de ideas se debería agregar como issues e etiquetar a la gente. Sugiero que no se agregue a la main cosas por hacer.

2022-03-19 00:18 UTC, texsmv requested changes
Remove incomplete sections.

2022-03-29 15:05 UTC, ChrisChV approved these changes
@jhuni45 hay algunas cosas que faltan por definir y colocar. Si no se van a hacer en esta versión habría que crear tareas para ello. Le doy el approve al ser la primera vesión de este documento :+1:

2022-04-02 01:14 UTC, texsmv approved these changes

2022-04-04 14:56 UTC, ChrisChV commented
@juanleondev You review is missing here

2022-04-05 22:29 UTC, juanleondev requested changes

2022-04-05 22:31 UTC, juanleondev commented
@ChrisChV @jhuni45 I left some comments. They have not yet been resolved. I forgot to request changes.

2022-04-06 01:35 UTC, jhuni45 commented on paulonia/processes/vacation.md
> ++ Tu reserva de vacaciones no debe ser inferior a 1 semana (5 días hábiles)
se va a poner en una sección nuevo de dias de descanso especiales. en la segunda version

2022-04-06 01:37 UTC, jhuni45 commented on paulonia/processes/vacation.md
> +1. Verifica en el [Calendario Paulonia](https://github.com/PauloniaAQP/paulonia_handbook/blob/main/contribute/example.md) que alguien más no haya reservado tus días de descanso
@juanleondev por eso menciono que en caso exista al menos una persona en su area lo consulte con su Team Lead

2022-04-09 21:41 UTC, ChrisChV commented on paulonia/processes/vacation.md
> ++ Tu reserva de vacaciones no debe ser inferior a 1 semana (5 días hábiles)
@jhuni45 Esa segunda versión tendría que ser prioritaria, porque siento que los empleados tendrán estas mismas preguntas

2022-04-09 21:46 UTC, ChrisChV commented on paulonia/processes/vacation.md
> +1. Verifica en el [Calendario Paulonia](https://github.com/PauloniaAQP/paulonia_handbook/blob/main/contribute/example.md) que alguien más no haya reservado tus días de descanso
@jhuni45 Ahora lo veo, existe una contradicción, porque si parece que se restringe a que revises que nadie haya tomado tus diás, creo que mejor sería. 

```suggestion
1. Verifica en el [Calendario Paulonia](https://github.com/PauloniaAQP/paulonia_handbook/blob/main/contribute/example.md) si hay más personas de tu área que están tomando vacaciones los mismo días que tú. Recuerda cumplir el primer pre-requisito.
```

2022-04-09 21:47 UTC, ChrisChV commented
@jhuni45 Dejé algunas respuestas en los comentarios de Juan

2022-04-12 15:58 UTC, juanleondev approved these changes

2022-04-12 15:58 UTC, juanleondev commented
@ChrisChV @jhuni45 Listo, ya está aprobado de mi parte tambien

2022-04-12 16:06 UTC, ChrisChV commented
@jhuni45 comentame si se hará un nuevo commit con lo conversado en [slack](https://paulonia.slack.com/archives/C02TE7HFFG8/p1649775362814609). Deme luz verde cuando pueda desplegar estos cambios

2022-04-20 00:49 UTC, merged