Security section
PauloniaAQP/paulonia_handbook pull request #6
Opened 2022-03-16 15:25 UTC by ChrisChV

2022-03-16 16:01 UTC, jhuni45 approved these changes

2022-03-17 15:37 UTC, juanleondev requested changes

2022-03-17 15:37 UTC, juanleondev commented on paulonia/security/vault_admins.md
> +Si no eres team lead o administrador de Vault, entonces no es necesario que leas este documento. Los team lead y administradores son los encargados de crear secretos y compartir secretors en Vault. A
secretos*

2022-03-19 00:30 UTC, texsmv approved these changes

2022-03-24 15:07 UTC, ChrisChV commented on paulonia/security/index.md
> +- Evitar usar cuentas críticas o información que pueda ser comprometida.
@jhuni45 Voy a detallar mejor lo que se puede considerar una cuenta crítica y que no. Serían las cuentas que tengan información o código de Paulonia o de algún cliente. Cuentas de redes sociales creo que no son tan críticas, a menos de que sean de clientes o de que tengamos información muuy importante o de que con esas cuentas puedas entrar a otras que si son críticas

2022-03-24 20:19 UTC, juanleondev approved these changes

2022-04-04 14:58 UTC, merged