Initial payment section
PauloniaAQP/paulonia_handbook pull request #8
Opened 2022-03-29 11:55 UTC by juanleondev

- Cuentas de Paulonia
- Detracciones
- Preguntas y Respuestas

2022-04-01 14:00 UTC, jhuni45 approved these changes

2022-04-04 15:30 UTC, ChrisChV requested changes
@juanleondev :+1: Creo que hay que mover este documento a otra carpeta. Creo que debería ir dentro de `paulonia/processes/payment/index`

2022-04-04 15:30 UTC, ChrisChV commented on payment/index.md
> +
@juanleondev Otra pregunta que suele surgir aquí es la de qué tipo de cambio se usa al momento de convertir usd a soles al momento de pagar las detracciones

2022-04-04 19:46 UTC, jhuni45 approved these changes

2022-04-05 22:49 UTC, juanleondev commented
@ChrisChV I did some changes based on your comments. Check pls

2022-04-09 21:35 UTC, ChrisChV approved these changes

2022-04-26 14:07 UTC, ChrisChV commented
@texsmv Quick reminder that your review is missing here :slightly_smiling_face:

2022-04-26 16:31 UTC, texsmv approved these changes
LGTM

2022-04-26 16:32 UTC, merged