Scrum process
PauloniaAQP/paulonia_handbook pull request #9
Opened 2022-03-29 15:50 UTC by juanleondev

2022-04-04 15:38 UTC, ChrisChV requested changes
@juanleondev Esta bien como primera vesión. Igual, hay que mover este documento dentro de otra carpeta (puede ser `paulonia/proceses`). Igual siento que aquí hay que empatar algunas cosas que está trabajando @jhuni45 actualmente

2022-04-04 15:38 UTC, ChrisChV commented on SCRUM/index.md
> +Es un evento de 15 minutos donde el equipo sincroniza sus actividades y crea un plan para las próximas 24 horas. Es importante entender que no solamente se debe dar una actualización de las tareas qu
@juanleondev Acá faltaría especificar en algún lado que estas reuniciones se hacer por teams por proyectos

2022-04-04 15:38 UTC, ChrisChV commented on SCRUM/index.md
> +- Las tareas son creadas generalmente por el **lider de equipo** pero tambien hay algunas que pueden ser creadas por cualquier persona del equipo (subtareas, tareas desde Slack
```suggestion
- Las tareas son creadas generalmente por el **lider de equipo** pero tambien hay algunas que pueden ser creadas por cualquier persona del equipo (subtareas, tareas desde Slack)
```

2022-04-04 15:38 UTC, ChrisChV commented on SCRUM/index.md
> +- **Sprint Futuro** Se crean en cualquier momento y se añaden al Backlog.
```suggestion
- **Sprint Futuro:** Se crean en cualquier momento y se añaden al Backlog.
```

2022-04-04 18:33 UTC, jhuni45 commented on SCRUM/index.md
> +Es la persona que ayuda a facilitar scrum al equipo, asegurándose de que se sigue el marco de trabajo. Su compromiso es con los valores y prácticas de scrum, pero también debe ser flexible y estar ab
```suggestion
Es la persona que ayuda a facilitar SCRUM al equipo, asegurándose de que se sigue el marco de trabajo. Su compromiso es con los valores y prácticas de scrum, pero también debe ser flexible y estar abierto a las oportunidades de mejora del flujo de trabajo del equipo
```

2022-04-04 19:07 UTC, jhuni45 requested changes

2022-04-04 19:07 UTC, jhuni45 commented on SCRUM/index.md
> +En Paulonia tenemos diferentes clientes, los cuales generalmente no tienen a alguien que asuma el rol de dueño de producto, es por ello que  designamos a una persona para que cumpla este rol en todos
```suggestion
En Paulonia tenemos diferentes clientes, los cuales generalmente no tienen a alguien que asuma el rol de dueño de producto, es por ello que designamos a una persona para que cumpla este rol en todos los proyectos, y se encargue de priorizar tareas y revisar la entrega de producto que hacen los equipos.
```

2022-04-04 19:07 UTC, jhuni45 commented on SCRUM/index.md
> +Se deben tener todas las tareas de clientes definidas hasta el lunes de la segunda semana. Ese día se celebrará una reunión corta con los líderes de equipo para definir que otras tareas se añadirán a
Creo que esto cambiaría no? no recuerdo que se haya aplicado mas que solo una vez. Tendriamos que poner que son los jueves donde se definen estas tareas con los lideres

2022-04-04 19:07 UTC, jhuni45 commented on SCRUM/index.md
> +Luego de que todas las tareas estén definidas el dia de la retrospectiva se seleccionará con todo el equipo las tareas que se harán en el siguiente sprint.
no hacemos esto, tal vez te refieres al sprint review

2022-04-05 22:56 UTC, juanleondev commented on SCRUM/index.md
> +Es la persona encargada de crear las historias de usuario que se trabajaran en los sprints. Conoce muy bien del negocio y es el puente entre el cliente y Paulonia
@jhuni45 A que rol te refires del lado de Paulonia? Scrum o Product Owner?

2022-04-05 23:19 UTC, juanleondev commented on SCRUM/index.md
> +Luego de finalizada su intervención deberá indicar el nombre de la siguiente persona.
@jhuni45 Te refieres a la ultima linea o a todo?

2022-04-08 17:21 UTC, juanleondev commented
@jhuni45 @ChrisChV Check the last commit pls. I have updated the document following your suggestions

https://github.com/PauloniaAQP/paulonia_handbook/pull/9/commits/d58703b8c002a78cbe9aa1017d860b70c1cb88ec

2022-04-09 21:56 UTC, ChrisChV approved these changes
:+1: De mi lado todas las dudas y cambios han sido resueltos

2022-04-11 13:43 UTC, jhuni45 commented on SCRUM/index.md
> +Es la persona encargada de crear las historias de usuario que se trabajaran en los sprints. Conoce muy bien del negocio y es el puente entre el cliente y Paulonia
@juanleondev Product owner

2022-04-11 21:41 UTC, texsmv approved these changes
Me gusto, solo una duda, el líder de proyecto es el mismo para todos los proyectos ?

2022-04-12 16:08 UTC, ChrisChV commented
@jhuni45 Falta tu review y aprovación aquí. No estoy seguro si todas las conversaciones están resueltas. Si falta que @juanleondev resuelva algo, indicarlo plz.

2022-04-12 21:15 UTC, jhuni45 approved these changes

2022-04-12 23:16 UTC, merged